config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  get 'books', to: 'books#index'
  get '/books/new', to: 'books#new'
  post '/books', to: 'books#create'
  get 'books/:id', to: 'books#show'
  get '/books/:id/edit', to: 'books#edit', as: 'edit_book'
  patch '/books/:id', to: 'books#update'
  delete '/books/:id/delete', to: 'books#destroy', as: 'delete_book'
  get  '/books/:id/delete', to: 'books#destroy'
=======
<<<<<<< HEAD
  get 'hello', to: 'welcome#hello'
  get 'books', to: 'books#index'
=======

>>>>>>> 9081f2e25557621276dfae85d109995c38fb2afd
>>>>>>> b96fa26bcabff0207031c5fbd1e65538220223b1
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
<<<<<<< HEAD
  validates :name, presence: true
  validates :author, presence: true
=======
>>>>>>> b96fa26bcabff0207031c5fbd1e65538220223b1
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
>>>>>>> 9081f2e25557621276dfae85d109995c38fb2afd
>>>>>>> b96fa26bcabff0207031c5fbd1e65538220223b1
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
<<<<<<< HEAD
    Rails.logger.info "All books #{@books.inspect}"
  end

  def new
    @book = Book.new
    Rails.logger.info "Book #{@book.inspect}"


  end

  def create
    Rails.logger.info "Params: #{params.inspect}"
    p params['book']
    # p book = Book.create(name: params['book']['name'], author: params['book']['author'])
   @book = Book.new(name: params['book']['name'], author: params['book']['author'])
    if @book.save
      redirect_to books_path
    else
      render action: :new
    end

  end

  def show

  end

  def edit
    p 'Triggering'
    p params['id']
    @book = Book.find(params['id'])
    Rails.logger.info "Book #{@book.inspect}"
  end

  def update
    @book = Book.find(params['id'])
    if @book.update(name: params['book']['name'], author: params['book']['author'])
      redirect_to books_path
    else
      render action: :edit
    end

  end

  def destroy
    Book.find(params['id']).destroy
    redirect_to books_path
=======
>>>>>>> b96fa26bcabff0207031c5fbd1e65538220223b1
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def hello
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/delete.html.erb
<p> Hello</p>

app/views/books/edit.html.erb
<p>Update Book</p>
<% if @book.errors.any? %>
<ul>
  <% @book.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<%= form_for @book, url: { action: "update" } do |f| %>
   Name: <%= f.text_field :name %> <br><br>
   Author: <%= f.text_field :author %> <br><br>
   <%= submit_tag 'Update' %>
   <% end %>

app/views/books/index.html.erb
<<<<<<< HEAD
=======

>>>>>>> b96fa26bcabff0207031c5fbd1e65538220223b1
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
<<<<<<< HEAD
      <th colspan="2"></th>
=======
>>>>>>> b96fa26bcabff0207031c5fbd1e65538220223b1
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
<<<<<<< HEAD
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'delete', delete_book_path(book) %></td>
=======
>>>>>>> b96fa26bcabff0207031c5fbd1e65538220223b1
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
 <p>Create New Book</p>
 <% if @book.errors.any? %>
 <ul>
   <% @book.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
 </ul>
 <% end %>
 <%= form_for @book, url: { action: "create" } do |f| %>
    Name: <%= f.text_field :name %> <br><br>
    Author: <%= f.text_field :author %> <br><br>
    <%= submit_tag 'Create' %>
    <% end %>

app/views/books/show.html.erb
Book created

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> b96fa26bcabff0207031c5fbd1e65538220223b1
  <head>
    <title>LearningRuby1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
<<<<<<< HEAD
=======
=======
<head>
  <title>LearningRuby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
>>>>>>> 9081f2e25557621276dfae85d109995c38fb2afd
>>>>>>> b96fa26bcabff0207031c5fbd1e65538220223b1
</html>

app/views/welcome/hello.html.erb
<p>Welcome to rails application</p>